services:
  dataflow-server:
    volumes:
      - ./lib/spring-cloud-dataflow-quartz-scheduler-1.0-SNAPSHOT.jar:/workspace/BOOT-INF/lib/spring-cloud-dataflow-quartz-scheduler-1.0-SNAPSHOT.jar
    environment:
      # SCDF Scheduler Configuration
      - SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED=true
      - SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED=true
      - SPRING_CLOUD_DATAFLOW_TASK_SCHEDULER_LOCAL_PLATFORM_TYPE=quartz
      # Quartz Configuration
      - SPRING_QUARTZ_JOB_STORE_TYPE=jdbc
      - SPRING_QUARTZ_JDBC_INITIALIZE_SCHEMA=always
      - SPRING_QUARTZ_AUTO_STARTUP=true
      # PostgreSQL Quartz Configuration
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_DRIVERDELEGATE_CLASS=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_CLASS=org.quartz.impl.jdbcjobstore.JobStoreTX
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_USEPROPERTIES=true
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_SCHEDULER_INSTANCENAME=spring-cloud-dataflow-scheduler
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_SCHEDULER_INSTANCEID=AUTO
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_TABLEPREFIX=QRTZ_
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_JOBSTORE_ISCLUSTERED=true
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_THREADPOOL_CLASS=org.quartz.simpl.SimpleThreadPool
      - SPRING_QUARTZ_PROPERTIES_ORG_QUARTZ_THREADPOOL_THREADCOUNT=10
      # Logging Configuration
      # - LOGGING_LEVEL_COM_GITHUB_THKWAG_SPRING_CLOUD_DATAFLOW_LOCAL_SCHEDULER=DEBUG